<?php
/**
 * Modify the content of the generated selection text file.
 *
 * The file contains the client's name, approval fields, and selected image
 * filenames. Append or prepend custom text, or replace the content entirely.
 *
 * @param string $content         The current file content.
 * @param int    $_collection_id  The collection ID (unused in this example).
 * @return string The modified file content.
 */
add_filter( 'picu_proof_file_content', function( $content, $_collection_id ) {
	$content .= "\n\n---\nGenerated by My Studio · example.com";
	return $content;
}, 10, 2 );
